# name: build-sphinx-to-gh-pages

# env:
#   GITHUB_ACTOR: eob
#   GITHUB_REPOSITORY: nludb/python-client
#   GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}

# on: 
#   push:
#     branches: [ main ]

# jobs:
#   build_sphinx_job:
#     runs-on: ubuntu-latest
#     container: debian:buster-slim

#     steps:
#       - name: Get prerequisites and clone repository
#         env:
#           GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
#         run: |
#           set -x
#           apt-get update
#           apt-get install -y git
#           git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
#         shell: bash

#       - name: Run build script for Sphinx pages
#         env:
#           GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
#         run: "docs/buildsite.sh"
#         shell: bash