name: Test

on:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - main
      - staging

jobs:
  test:
    name: Run test suite
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Virtualenv
        run: |
          python3 -m venv .venv
      - name: Activate Virtualenv
        run: |
          source .venv/bin/activate
      - name: Install Development Dependencies
        run: |
          python -m pip install -r requirements.dev.txt
      - name: Install Local Package
        run: |
          python -m pip install -e .
      - name: Run test suite (Steamship Prod)
        run: pytest
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          STEAMSHIP_API_KEY: ${{ secrets.STEAMSHIP_PROD_TEST_KEY }}
          STEAMSHIP_API_BASE: ${{ secrets.STEAMSHIP_PROD_TEST_API_BASE }}
          STEAMSHIP_APP_BASE: ${{ secrets.STEAMSHIP_PROD_TEST_APP_BASE }}
      - name: Run test suite (Steamship Prod)
        run: pytest
        if: ${{ github.ref == 'refs/heads/staging' }}
        env:
          STEAMSHIP_API_KEY: ${{ secrets.STEAMSHIP_STAGING_TEST_KEY }}
          STEAMSHIP_API_BASE: ${{ secrets.STEAMSHIP_STAGING_TEST_API_BASE }}
          STEAMSHIP_APP_BASE: ${{ secrets.STEAMSHIP_STAGING_TEST_APP_BASE }}